### ISSUE TITLE
null pointer error from MediaFailed event

### ISSUE THREAD

**Issue by K24A3** [Sascha-L/WPF-MediaKit#22]
I have not installed a codec for MKV files so I expect an M_MediaFailed error "Could not render any streams from the source Uri", which happens.

However there is a second M_MediaFailed error that comes through now after I updated WPFMediaKit from github. I assume this is the fallback triggering the 2nd M_MediaFailed event.

The 2nd error is a null exception, so we should add some error detecting in this area:

 M_MediaFailed - System.Exception: Could not render any streams from the source Uri
   at WPFMediaKit.DirectShow.MediaPlayers.MediaUriPlayer.oldOpenSource() in d:\Dev\CSharp\WPFMediaKit\DirectShow\MediaPlayers\MediaUriPlayer.cs:line 538

M_MediaFailed - System.NullReferenceException: Object reference not set to an instance of an object.
   at WPFMediaKit.DirectShow.MediaPlayers.MediaUriPlayer.OpenSource() in d:\Dev\CSharp\WPFMediaKit\DirectShow\MediaPlayers\MediaUriPlayer.cs:line 299

**Comment by xmedeko** [comment]
Do you have [codecs](/Sascha-L/WPF-MediaKit/wiki/Codecs) properly installed?
