### ISSUE TITLE
Crash when machine has no audio output

### ISSUE THREAD

**Issue by xmedeko** [Sascha-L/WPF-MediaKit#33]
When a machine has no audio card, the WPF Media Kit crashes with 
```System.Runtime.InteropServices.COMException (0x80040256): Cannot play back the audio stream: no audio hardware is available, or the hardware is not responding.
   at DirectShowLib.DsError.ThrowExceptionForHR(Int32 hr)
   at WPFMediaKit.DirectShow.MediaPlayers.MediaPlayerBase.AddFilterByDevice(IGraphBuilder graphBuilder, DsDevice device)
   at WPFMediaKit.DirectShow.MediaPlayers.MediaPlayerBase.AddFilterByName(IGraphBuilder graphBuilder, Guid deviceCategory, String friendlyName)
   at WPFMediaKit.DirectShow.MediaPlayers.MediaUriPlayer.InsertAudioRenderer(String audioDeviceName)
   at WPFMediaKit.DirectShow.MediaPlayers.MediaUriPlayer.OpenSource()
```
See also http://stackoverflow.com/questions/24016776/wpf-mediakit-audio-issues

The player should not crash and should have a flag that the audio is not available.

**Comment by Sascha-L** [comment]
I am unable to reproduce this. The code around "InsertAudioRenderer" is in a try-catch-block, cause I already fixed this in the past. I also tried playing back a mp4 with no available audio device and it worked without any issues.

**Comment by xmedeko** [comment]
You are right, it's fixed already, sorry.
Just some need some flag that the audio cannot be played would be handy. Maybe the overlay stats #32 could do the job.
