### ISSUE TITLE
Could not create IMFVideoPresenter

### ISSUE THREAD

**Issue by JeremiSharkboy** [Sascha-L/WPF-MediaKit#93]
StackTrace:
```
   at WPFMediaKit.MediaFoundation.EvrPresenter.CreateNew()
   at WPFMediaKit.DirectShow.MediaPlayers.MediaPlayerBase.CreateEnhancedVideoRenderer(IGraphBuilder graph, Int32 streamCount)
   at WPFMediaKit.DirectShow.MediaPlayers.MediaPlayerBase.CreateVideoRenderer(VideoRendererType rendererType, IGraphBuilder graph, Int32 streamCount)
   at WPFMediaKit.DirectShow.MediaPlayers.MediaUriPlayer.oldOpenSource()
```

InnerException

`Can't load library '...\bin\Build\EvrPresenter64.dll'.`

Im using MediaUriElement to play RTSP stream. But i got exception: there are no EvrPresenter64.dll in my folder, actually it exists

How can i fix this

**Comment by henriknc** [comment]
Hi Jeremi,
Did you solve this problem. I have the exact same problem when trying to load the EvrPresenter32.dll library. It suddenly stopped working.

**Comment by henriknc** [comment]
Thanks for getting back to me so quickly. I already run on the x86 platform, so the cause of my problem must be different.

**Comment by vryan95** [comment]
Got the same problem. Cant load evrpresenter64.dll and when i build as x86, it cant load EvrPresenter32.dll. Both dll's are in the correct folder.

**Comment by henriknc** [comment]
I our case it was because the C++ 2013 redistributable was not installed on the pc.

**Comment by vryan95** [comment]
Tried that but doesn't solve the problem. Guess I'll continue my search. Thanks anyway
